package com.demo.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2020-03-21T19:20:58.063-05:00
 * Generated source version: 3.3.3
 *
 */
@WebServiceClient(name = "ApplicationServiceSOAP",
                  wsdlLocation = "http://192.168.1.165:8080/javaee-soap/ApplicationServiceSOAP?wsdl",
                  targetNamespace = "http://soap.demo.com/")
public class ApplicationServiceSOAP extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.demo.com/", "ApplicationServiceSOAP");
    public final static QName ApplicationServicePort = new QName("http://soap.demo.com/", "ApplicationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.165:8080/javaee-soap/ApplicationServiceSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ApplicationServiceSOAP.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.165:8080/javaee-soap/ApplicationServiceSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ApplicationServiceSOAP(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ApplicationServiceSOAP(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApplicationServiceSOAP() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ApplicationServiceSOAP(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ApplicationServiceSOAP(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ApplicationServiceSOAP(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IApplicationService
     */
    @WebEndpoint(name = "ApplicationServicePort")
    public IApplicationService getApplicationServicePort() {
        return super.getPort(ApplicationServicePort, IApplicationService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IApplicationService
     */
    @WebEndpoint(name = "ApplicationServicePort")
    public IApplicationService getApplicationServicePort(WebServiceFeature... features) {
        return super.getPort(ApplicationServicePort, IApplicationService.class, features);
    }

}
