package com.demo.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2020-03-21T19:20:58.026-05:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://soap.demo.com/", name = "IApplicationService")
@XmlSeeAlso({ObjectFactory.class})
public interface IApplicationService {

    @WebMethod
    @RequestWrapper(localName = "getApplication", targetNamespace = "http://soap.demo.com/", className = "com.demo.client.GetApplication")
    @ResponseWrapper(localName = "getApplicationResponse", targetNamespace = "http://soap.demo.com/", className = "com.demo.client.GetApplicationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.demo.client.Application getApplication(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "updateApplication", targetNamespace = "http://soap.demo.com/", className = "com.demo.client.UpdateApplication")
    @ResponseWrapper(localName = "updateApplicationResponse", targetNamespace = "http://soap.demo.com/", className = "com.demo.client.UpdateApplicationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean updateApplication(

        @WebParam(name = "arg0", targetNamespace = "")
        com.demo.client.Application arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAll", targetNamespace = "http://soap.demo.com/", className = "com.demo.client.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://soap.demo.com/", className = "com.demo.client.GetAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.demo.client.Application> getAll()
;

    @WebMethod
    @RequestWrapper(localName = "addApplication", targetNamespace = "http://soap.demo.com/", className = "com.demo.client.AddApplication")
    @ResponseWrapper(localName = "addApplicationResponse", targetNamespace = "http://soap.demo.com/", className = "com.demo.client.AddApplicationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean addApplication(

        @WebParam(name = "arg0", targetNamespace = "")
        com.demo.client.Application arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteApplication", targetNamespace = "http://soap.demo.com/", className = "com.demo.client.DeleteApplication")
    @ResponseWrapper(localName = "deleteApplicationResponse", targetNamespace = "http://soap.demo.com/", className = "com.demo.client.DeleteApplicationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean deleteApplication(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
